---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
  - name: demo-app-http
    port: 80
    protocol: TCP
    nodePort: 30080
  selector:
    app: demo-app
